### ISSUE TITLE
Suggestion: show how many of the current thing you need to make in non-combat to reach desired level.

### ISSUE THREAD

**Issue by badgehunter** [Boldy97/ironwood-scripts#11]
like for example this currently shows how long i have till my target level, aka 25. and then at time page it shows how long current things i have last. like maybe there could be at goal level or tier up a thing to show how many of those things i need to make to reach that level.

![image](https://github.com/user-attachments/assets/a6e1d5f0-acaa-4d27-a81f-2f0d4e39ef16)

![image](https://github.com/user-attachments/assets/3bef7f35-82c6-462a-a64a-c6666ba7716e)

**Comment by Boldy97** [comment]
Hey!

I had this written down already here:
https://trello.com/c/hVMceRN6/19-add-actions-to-next-tier-level

I prioritized it, so it's something that should come very soon 😄

**Comment by Boldy97** [comment]
This is now implemented here, and will be available in the next release
https://github.com/Boldy97/ironwood-scripts/commit/f751bf543d37da40d7aadd6ba16e6a4cefe1ba1e
