### ISSUE TITLE
[Feature request] Allow local file URLs for animated loot background.

### ISSUE THREAD

**Issue by gomhaille** [Boldy97/ironwood-scripts#15]
Could you please make it so that I can use a file on my PC for the background, instead of needing to upload it to a remote server?
For example, `file:///C:/root/img/gifs/test_gif1.gif` should work, but it does not.

As a semi-unrelated side note, do `.mp4` files work as well? I noticed that `.webm` was listed in the example file extensions, and it does say "etc." at the end, but I figured I would still ask anyway.

**Comment by Boldy97** [comment]
That's not possible in the way you suggest it,
but I will test around with opening a file selector menu to select a local file.

**Comment by gomhaille** [comment]
I honestly don't know much of anything about how this stuff works, so I appreciate you being willing to look into this as an option regardless. 

My initial suggestion for using `file:///C:<path>` was because that's how browsers load local files. Here's an example if wanted: 

https://github.com/user-attachments/assets/c22ab8ae-1d36-4373-b3c3-6d2bf863f7bb

If the above has no relation to how it works on your end, then I apologise for being ignorant. I was making an assumption.

**Comment by gomhaille** [comment]
Right, uh... as per the v1.1 Ironwood update, I no longer wish to play, so I'll go ahead and close this.

Context:
![brave_WkJcLEDlnm](https://github.com/user-attachments/assets/c5eca601-ad0b-4927-9bae-837f1ae5b59e)
![brave_hH0n0sdFWs](https://github.com/user-attachments/assets/86298434-b205-48c7-b5b7-bd56d9f75fda)
