### ISSUE TITLE
Taming tab not working in 4.8.1

### ISSUE THREAD

**Issue by Cinerar** [Boldy97/ironwood-scripts#17]
userscript.html?name=Ironwood-RPG-Pancake-Scripts.user.js&id=**** Something went wrong Could not find id profitProducedRows in blueprint tamingEstimatorComponent

![image](https://github.com/user-attachments/assets/4a3d2307-98c6-4070-bba5-0823b58cc12e)

**Comment by Boldy97** [comment]
@Cinerar This was fixed in v4.9.0
https://github.com/Boldy97/ironwood-scripts/commit/e622fdc6c9204484479bd49fd30b320ae8b122d7
