### ISSUE TITLE
Stat Redesign for Pets removes collection type tags.

### ISSUE THREAD

**Issue by feyyd** [Boldy97/ironwood-scripts#19]
When using the stats redesign for pets, the tags for the resources said pet collects are removed (ie Veges 1 Bones 1)

Ideally these tags would stay in addition to the stat redesign (I love it!).

**Comment by Boldy97** [comment]
I just added this as a toggle for the pet stat redesign, will be rolled out in the next version!

[Trello](https://trello.com/c/SVs44jJj/68-pet-stat-redesign-restyle)
[Commit](https://github.com/Boldy97/ironwood-scripts/commit/790679a07b5c15e06fbd37b38b3f713b4b012420)

**Comment by feyyd** [comment]
Thanks!
